name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        JSON_MATRIX="{ \"include\": [] }"
        while IFS="=", read -r ARCH BIN
        do
            JSON_MATRIX=$(echo "$JSON_MATRIX" | jq ".include += [
                {\"arch\": \"$ARCH\",\"bin\": \"$BIN\"} ]")
        done < MAP_ARCH_TRANSLATOR
        echo "::set-output name=matrix::$JSON_MATRIX"
  debug:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ needs.pre-build.outputs.matrix }}


  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: user/app:latest
