name: ci

on:
  push:
    branches:
      - 'master'
      - 'feat-*'

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      bin_version: ${{ steps.set-bin-version.outputs.bin_version }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: set-matrix
      name: set-matrix
      run: |
        .github/workflows/ci.generate_json_matrix.sh
    - id: set-bin-version
      name: set-bin-version
      run: |
        PAGE_URL="https://www.speedtest.net/apps/cli#linux-flyout"
        PAGE_CONTENT=$(curl $PAGE_URL 2>/dev/null)

        LATEST_VERSION=$( echo "$PAGE_CONTENT" | grep -Poh "https:\/\/install\.speedtest\.net\/app\/cli\/ookla-speedtest-\d+\.\d+\.\d+-x86_64-linux\.tgz" | rev | cut -d / -f 1 | rev | cut -d "-" -f 3)

        echo "::set-output name=bin_version::$LATEST_VERSION"

  docker:
    needs: pre-build
    strategy:
      matrix: ${{ fromJson(needs.pre-build.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.arch }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/speedtest-cli:latest,${{ secrets.DOCKERHUB_USERNAME }}/speedtest-cli:${{ needs.pre-build.outputs.bin_version }}
          build-args: |
            binVersion=${{ needs.pre-build.outputs.bin_version }}
            binArch=${{ matrix.bin_arch }}
